Add support for HTML file to extract-regexes.pl
davisjam/vuln-regex-detector pull request #77
Opened 2021-06-26 02:44 UTC by du201

### Summary
extract-regexes.pl used to only support python and js files. I added support for html files so that now extract-regexes.pl can process three types of files

### Implementation Details
The input html file is first processed by beautifulsoup to combine all of its script tags' content into a new, temporary js file. Then, that js file is fed into the already-existing javascript extractor. After it's done, the temporary js file is deleted. A new test for html file is also created in ./src/extract/test/html

2021-06-28 16:41 UTC, davisjam commented on src/extract/extract-regexes.pl
> +  if ($language eq "html") {
As discussed: I suggest you try an implementation for the html-extractor that recursively calls the meta-program to request JS extraction, and then parses its results.

2021-06-30 15:03 UTC, du201 commented on src/extract/src/html/extract-regexps-html.py
> +output = subprocess.run(['./src/javascript/extract-regexps.js', './src/html/temp-js-content.js'], capture_output=True, text=True)
The only concern that I still have is that the location of the js regex extractor is hardcoded in the html regex extractor. I thought about letting the meta-program pass the location to the html regex extractor, but that would require creating a special case for html file in the meta-program, which I think would create the modular design.

2021-06-30 16:44 UTC, davisjam requested changes

2021-06-30 16:44 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +# create temp-js-content.js based on the location of extract-regexes.pl
This will not work well if multiple instances of vuln-regex-detector are invoked concurrently. Use the Python tempfile library to make a temp dir.

2021-06-30 16:44 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +js_from_html = ''
Is it appropriate to merge all of the JS script tags like this, or would it be better to make one file per <script>? I am not sure the DOM JS semantics, could we get compilation failures as a result?

2021-06-30 16:44 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +# call the meta-program
Please use functions, e.g. one called "extractScriptTags" that returns an array of JS snippets, and e.g. one called "extractRegexes".

2021-06-30 17:53 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +    output = subprocess.run(['./extract-regexes.pl', json_tempfile.name],
PTAL https://stackoverflow.com/questions/918154/relative-paths-in-python

2021-06-30 17:54 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +js_tempfile.seek(0)
Why?

2021-06-30 17:54 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +json_tempfile.seek(0)
Why seek? You do not use this object again.

2021-06-30 17:55 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +
There should be a function to query the meta- tool...

2021-07-12 17:13 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +# create temp json file to pass to the meta-program
This bit -- composing the input file for the meta-tool -- should be part of the function `extract_regexes`.

2021-07-12 17:15 UTC, davisjam commented on src/extract/src/html/extract-regexps-html.py
> +print(extract_regexes(json_tempfile, file_path), end = '')
I forget, does this output include the name of the file being scanned? (which you are about to delete)? What are the implications for users?

Should we (1) name the temp file more uniquely, and then (2) run a search-replace on the returned data to use the name of the original HTML file instead?

2021-07-12 18:10 UTC, merged

2021-07-12 18:10 UTC, davisjam commented
LGTM, thank you.